### PR TITLE
Husky & lint staged pre-commit hooks added, eslint, prettier, fixed types & linting problems

### PR DESCRIPTION
**Pull request by iarmankhan**
#32 

fixed almost all linting & types error, added strict eslint and types rules. Added prettier to format code.

### CODE REVIEW

**Comment by ehsan6sha** [comment]
Thanks to @iarmankhan

**Comment by ehsan6sha** [comment]
@iarmankhan After merging it, I tested and application could not load. Not sure where the blocker was, but should be in RenderPhotos I think. If you get some time please check it, I also check when I get some free time. Also since I made some changes after your pull request, I had to manually resolve some conflicts, so that could I made an error by mistake too

**Comment by iarmankhan** [comment]
Okay that's strange. I'll surely look in to the issue today and try to fix it by end of the day. Thank you.

**Comment by ehsan6sha** [comment]
> Okay that's strange. I'll surely look in to the issue today and try to fix it by end of the day. Thank you.

Thank you. I hope it was not my merge changes which broke your code, or else I owe you a coffee ;)

**Comment by ehsan6sha** [comment]
There were 4 files under component that I changed

**Comment by iarmankhan** [comment]
From quick debugging I can say `getMedia` function in `PhotosContainer.tsx` is broken.

**Comment by iarmankhan** [comment]
```
useEffect(() => {
    let boxPhotos: Array<MediaLibrary.Asset> = getUserBoxMedia('');
    if (storagePhotos) {
      setPhotos([...boxPhotos, ...storagePhotos]);
    }
  }, [storagePhotos]);
```

this code is broken!!!

**Comment by iarmankhan** [comment]
Hey @ehsan6sha 
can you please reverted this pull, I guess more than one thing is broken and I couldn't find the main cause of the problem yet. I'll keep trying to fix it and create a PR. Sorry for this. Thank you

**Comment by ehsan6sha** [comment]
> Hey @ehsan6sha
> can you please reverted this pull, I guess more than one thing is broken and I couldn't find the main cause of the problem yet. I'll keep trying to fix it and create a PR. Sorry for this. Thank you

Yes, I already reverted it. Thanks for the help. I'm working on some performance issues and will take a look after it too

**Comment by iarmankhan** [comment]
Okay, so far I figured out that this is some component re-rendering infinite times or until the app crash. Must be some useEffect / setState issue. In my branch I've also converted many functions to use `useCallback` maybe that is causing problem?!

**Comment by ehsan6sha** [comment]
> Okay, so far I figured out that this is some component re-rendering infinite times or until the app crash. Must be some useEffect / setState issue. In my branch I've also converted many functions to use `useCallback` maybe that is causing problem?!

I think that is the issue. I am doing some improvements by removing or changing the unnecessary states, which should improve performance and this issue. Let's revisit this after the improvements are made in 2-3 days. Thank you for this :) Let me know if any other issue caught your eyes ;)

**Comment by ehsan6sha** [comment]
@iarmankhan the changes are done and time if you want to run your magic ;)

**Comment by iarmankhan** [comment]
@ehsan6sha that's great! I'll create a new branch now for eslint.

**Pull request merged**
